![](../storage/banners/40_assumptions.png)

##### Быстродействие

`clip`: своё лучше для обычных чисел

In [43]:
from __init__ import *
import numpy as np
import time

n = int(1e6)

# Моя функция
def clip(a: float, bot: float, top: float) -> float:
    if a < bot:
        return bot
    if a > top:
        return top
    return a

t0 = time.time()
for _ in range(n):
    tmp = clip(-1, 0, 2)
print(f"my-clip: {time.time() - t0} секунд")

t0 = time.time()
for _ in range(n):
    tmp = np.clip(-1, 0, 2)
print(f"np.clip: {time.time() - t0} секунд")

my-clip: 0.14356112480163574 секунд
np.clip: 3.1530544757843018 секунд


In [ ]:
# import numpy as np
# s0 = dir(np)

In [ ]:
# s = dir(quaternion.np)
# for i in s0:
#     s.remove(i)
# s

**Инициализация**

In [18]:
import numpy as np
import quaternion

for q in [np.quaternion(1, 0, 0, 0),
          np.quaternion(1, 2, 3, 4),
          np.quaternion(5, 0, 0),
          np.quaternion(5),
          np.quaternion()]:
    print(f"q = {q}")

q = np.quaternion(1, 2, 3, 4)

q = quaternion(1, 0, 0, 0)
q = quaternion(1, 2, 3, 4)
q = quaternion(0, 5, 0, 0)
q = quaternion(5, 0, 0, 0)
q = quaternion(0, 0, 0, 0)


In [28]:
a = np.array([0, 0, 0.5])

q1 = quaternion.from_vector_part(a)
q2 = quaternion.from_euler_angles(a)

q3 = np.quaternion(np.sqrt(1 - np.linalg.norm(a)**2), *a)

print(f"Кватернион из вектора: {q1}")
print(f"Кватернион единичный из вектора: {q3}")
print(f"Кватернион из углов Эйлера: {q2}")

Кватернион из вектора: quaternion(0, 0, 0, 0.5)
Кватернион единичный из вектора: quaternion(0.866025403784439, 0, 0, 0.5)
Кватернион из углов Эйлера: quaternion(0.968912421710645, 0, 0, 0.247403959254523)


**Преобразования типов**

In [66]:
a = quaternion.as_float_array(q)
b = quaternion.np.array(q)
c = quaternion.np.asarray(q)
d = q.components

print(f"Как numpy-массив: {a}")
print(type(a))
print(f"Как numpy-массив: {b}")
print(type(b))
print(f"Как numpy-массив: {c}")
print(type(c))
print(f"Как numpy-массив: {d}")
print(type(d))

Как numpy-массив: [1. 2. 3. 4.]
<class 'numpy.ndarray'>
Как numpy-массив: quaternion(1, 2, 3, 4)
<class 'numpy.ndarray'>
Как numpy-массив: quaternion(1, 2, 3, 4)
<class 'numpy.ndarray'>
Как numpy-массив: [1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [132]:
a = np.array([4, 5, 6, 7])

anw1 = np.append(a, q)
anw2 = np.append(a, q.components)

print(f"Плохой пример: {anw1}")
print(f"Хороший пример: {anw2}")

Плохой пример: [quaternion(4, 0, 0, 0) quaternion(5, 0, 0, 0) quaternion(6, 0, 0, 0)
 quaternion(7, 0, 0, 0) quaternion(1, 2, 3, 4)]
Хороший пример: [4. 5. 6. 7. 1. 2. 3. 4.]


**Преобразовани математические**

In [101]:
a = q.real
b = q.vec
w = q.w
x = q.x
y = q.y
z = q.z

print(f"Скалярная часть: {a}")
print(type(a))
print(f"Векторная часть: {b}")
print(type(b))
print(f"Составлющие: {w} {x} {y} {z}")
print(type(w), type(x), type(y), type(z))

Скалярная часть: 1.0
<class 'float'>
Векторная часть: [2. 3. 4.]
<class 'numpy.ndarray'>
Составлющие: 1.0 2.0 3.0 4.0
<class 'float'> <class 'float'> <class 'float'> <class 'float'>


In [103]:
a = quaternion.np.normalized(q)
b = q.normalized()

print(f"Нормированный кватернион: {a} | {b}")
print(type(a), type(b))

Нормированный кватернион: quaternion(0.182574185835055, 0.365148371670111, 0.547722557505166, 0.730296743340221) | quaternion(0.182574185835055, 0.365148371670111, 0.547722557505166, 0.730296743340221)
<class 'quaternion.quaternion'> <class 'quaternion.quaternion'>


In [99]:
a = quaternion.np.abs(q)
b = quaternion.np.absolute(q)
d = q.abs()

c = quaternion.np.norm(q)

print(f"Модуль: {a} | {b} | {d}")
print(type(a), type(b), type(d), '\n')

print(f"Норма: {c} (√c = {np.sqrt(c)})")
print(type(c))

Модуль: 5.477225575051661 | 5.477225575051661 | 5.477225575051661
<class 'numpy.float64'> <class 'numpy.float64'> <class 'float'> 

Норма: 30.0 (√c = 5.477225575051661)
<class 'numpy.float64'>


In [27]:
a = quaternion.np.angle_of_rotor(q)
b = q.angle()

print(f"Угол поворота: {a} | {b}")
print(type(a), type(b))

Угол поворота: 4.389231563842282 | 4.389231563842282
<class 'numpy.float64'> <class 'float'>


In [96]:
a = q.conj()
b = q.conjugate()

с = q.inverse()
d = q.reciprocal()

print(f"Сопряженный: {a} | {b}")
print(type(a), type(b), '\n')

print(f"Обратный: {с} | {d}")
print(type(с), type(d))

Сопряженный: quaternion(1, -2, -3, -4) | quaternion(1, -2, -3, -4)
<class 'quaternion.quaternion'> <class 'quaternion.quaternion'> 

Обратный: quaternion(0.0333333333333333, -0.0666666666666667, -0.1, -0.133333333333333) | quaternion(0.0333333333333333, -0.0666666666666667, -0.1, -0.133333333333333)
<class 'quaternion.quaternion'> <class 'quaternion.quaternion'>


In [125]:
A = quaternion.as_rotation_matrix(q)
B = quaternion.as_rotation_matrix(q.normalized())

print(f"Матрица поворота из кватерниона A: \n{A}")
print(f"Матрица поворота из кватерниона B: \n{B}")

Матрица поворота из кватерниона A: 
[[-0.66666667  0.13333333  0.73333333]
 [ 0.66666667 -0.33333333  0.66666667]
 [ 0.33333333  0.93333333  0.13333333]]
Матрица поворота из кватерниона B: 
[[-0.66666667  0.13333333  0.73333333]
 [ 0.66666667 -0.33333333  0.66666667]
 [ 0.33333333  0.93333333  0.13333333]]


##### Проверка математики <u>вращения</u>

###### Умножение кватернионов

In [3]:
from __init__ import *
from sympy import *

q1 = kf.get_vars("q^1", 4, numb=False)
q2 = kf.get_vars("q^2", 4, numb=False)
q1v = Matrix(q1[1:4])
q2v = Matrix(q2[1:4])

print("Скалярная часть:")
q1[0]*q2[0] - q1v.dot(q2v)

Скалярная часть:


q^1_0*q^2_0 - q^1_x*q^2_x - q^1_y*q^2_y - q^1_z*q^2_z

In [4]:
print("Векторная часть:")
q1v*q2[0] + q2v*q1[0] + q1v.cross(q2v)

Векторная часть:


Matrix([
[q^1_0*q^2_x + q^1_x*q^2_0 + q^1_y*q^2_z - q^1_z*q^2_y],
[q^1_0*q^2_y - q^1_x*q^2_z + q^1_y*q^2_0 + q^1_z*q^2_x],
[q^1_0*q^2_z + q^1_x*q^2_y - q^1_y*q^2_x + q^1_z*q^2_0]])

###### Проверка угла поворота

$$\cos\alpha = \frac{1}{2} [ tr(S) - 1]$$ 

In [2]:
from __init__ import *
import numpy as np
import quaternion

q = np.quaternion(*np.random.uniform(-1, 1, 4)).normalized()
S = quaternion.as_rotation_matrix(q)

cos_alpha = kf.clip((np.trace(S) - 1) / 2, -1, 1)
print(f"Косинус по формуле: {cos_alpha}")
print(f"Косинус из модуля: {np.cos(quaternion.np.angle_of_rotor(quaternion.from_rotation_matrix(S)))}")

Косинус по формуле: 0.5884554447041483
Косинус из модуля: 0.5884554447041487


In [9]:
phi = var('varphi')
r = kf.get_vars(name='r', n=3, numb=False)

for q in [kf.vec2quat(kf.get_vars(name='q', n=3, numb=False)),
          kf.get_q_Rodrigue_Hamilton(phi=phi, r=r, symbol=True)]:
    print(f"При кватернионе")
    display(q.T)
    M = kf.quart2dcm(q)
    cos_s = kf.matrix2angle(M)
    print(f"косинус:")
    display(cos_s.simplify())

При кватернионе


Matrix([[sqrt(-q_x**2 - q_y**2 - q_z**2 + 1), q_x, q_y, q_z]])

косинус:


-2*q_x**2 - 2*q_y**2 - 2*q_z**2 + 1

При кватернионе


Matrix([[cos(varphi/2), r_x*sin(varphi/2)/sqrt(r_x**2 + r_y**2 + r_z**2), r_y*sin(varphi/2)/sqrt(r_x**2 + r_y**2 + r_z**2), r_z*sin(varphi/2)/sqrt(r_x**2 + r_y**2 + r_z**2)]])

косинус:


cos(varphi)

###### Сравнение старого и нового кода

<u>Старый код</u>

In [3]:
from __init__ import *
import numpy as np
import quaternion

def vec2quat_old(v) -> list:
    if len(v) != 3:
        raise ValueError(f"Подаётся вектор длинны {len(v)}, требуется длинна 3!")
    if np.linalg.norm(v) > 1:
        return [0] + list(np.array(v)/np.linalg.norm(v))
    else:
        return [np.sqrt(1 - np.linalg.norm(v)**2), v[0], v[1], v[2]]

def q_dot_old(L1, L2):
    return np.array([L1[0] * L2[0] - L1[1] * L2[1] - L1[2] * L2[2] - L1[3] * L2[3],
                     L1[0] * L2[1] + L1[1] * L2[0] + L1[2] * L2[3] - L1[3] * L2[2],
                     L1[0] * L2[2] + L1[2] * L2[0] + L1[3] * L2[1] - L1[1] * L2[3],
                     L1[0] * L2[3] + L1[3] * L2[0] + L1[1] * L2[2] - L1[2] * L2[1]])

def quart2dcm_old(L) -> np.ndarray:
    w, x, y, z = L
    A = np.eye(3)
    A[0][0] = 1 - 2 * y ** 2 - 2 * z ** 2
    A[0][1] = 2 * x * y + 2 * z * w
    A[0][2] = 2 * x * z - 2 * y * w
    A[1][0] = 2 * x * y - 2 * z * w
    A[1][1] = 1 - 2 * x ** 2 - 2 * z ** 2
    A[1][2] = 2 * y * z + 2 * x * w
    A[2][0] = 2 * x * z + 2 * y * w
    A[2][1] = 2 * y * z - 2 * x * w
    A[2][2] = 1 - 2 * x ** 2 - 2 * y ** 2
    return A

def check_quat(q1, q2, q_dot, quart2dcm, vec2quat):
    print(f"λ₁ = {q1}")
    if isinstance(q1, list | np.ndarray):
        print(f"q3->q4: {vec2quat(q1[1:4])}")
        if isinstance(vec2quat(q1[1:4]), list | np.ndarray):
            print(f"модуль {vec2quat(q1[1:4])} = {np.linalg.norm(vec2quat(q1[1:4]))})")
    if isinstance(q1, quaternion.quaternion):
        q_new = vec2quat(q1.vec)
        print(f"q3->q4: {q_new}")
        print(f"модуль {q_new} = {q_new.abs()})")
    print(f"λ₂ = {q2}")
    print(f"λ₁∘λ₂ = {q_dot(q1, q2)}\n")

    A = quart2dcm(q1)
    print(f"A(λ₁) = \n{A} (type(A)={type(A)}) \nДетерминант {np.linalg.det(A)}, \nAA.T=\n{np.round(A @ A.T).astype(np.int64)}")

qs = [np.random.rand(4) for _ in range(2)]
for i in range(2):
    qs[i] /= np.linalg.norm(qs[i])

check_quat(qs[0], qs[1], q_dot_old, quart2dcm_old, vec2quat_old)

λ₁ = [0.59379408 0.54259116 0.42124688 0.41899223]
q3->q4: [0.5937940769627631, 0.5425911603820692, 0.4212468812216982, 0.4189922336991132]
модуль [0.5937940769627631, 0.5425911603820692, 0.4212468812216982, 0.4189922336991132] = 1.0)
λ₂ = [0.14235516 0.08436462 0.80418151 0.57088503]
λ₁∘λ₂ = [-0.53920119  0.03087359  0.26307584  0.7994373 ]

A(λ₁) = 
[[ 0.29399315  0.95471988 -0.04558484]
 [-0.04046055  0.06008068  0.99737318]
 [ 0.95495077 -0.29137649  0.0562918 ]] (type(A)=<class 'numpy.ndarray'>) 
Детерминант 1.0000000000000007, 
AA.T=
[[1 0 0]
 [0 1 0]
 [0 0 1]]


<u>Новый код</u>

In [4]:
for i in range(2):
    qs[i] = np.quaternion(*qs[i])

In [5]:
import numpy as np
import quaternion

def vec2quat(v):
    """Перевод вектора кватерниона в кватернион"""
    if isinstance(v, np.ndarray):
        return np.quaternion(np.sqrt(1 - np.linalg.norm(v)**2), *v)
    else:
        from sympy import Matrix, sqrt
        return Matrix([sqrt(1 - v.dot(v)), v[0], v[1], v[2]])

def q_dot(q1, q2):
    """Умножение кватернионов длины 4"""
    if isinstance(q1, quaternion.quaternion):
        return q1 * q2
    else:
        from sympy import Matrix
        q1v = Matrix(q1[1:4])
        q2v = Matrix(q2[1:4])
        scalar = q1[0]*q2[0] - q1v.dot(q2v)
        vector = q1v*q2[0] + q2v*q1[0] + q1v.cross(q2v)
        return Matrix([scalar, vector[0], vector[1], vector[2]])

def quart2dcm(q):
    """Матрицу поворота из кватерниона поворота"""
    if isinstance(q, quaternion.quaternion):
        return quaternion.as_rotation_matrix(q)
    else:
        from sympy import Matrix, sqrt
        w, x, y, z = q
        return Matrix([[1 - 2*y**2 - 2*z**2, 2*x*y + 2*z*w, 2*x*z - 2*y*w],
                       [2*x*y - 2*z*w, 1 - 2*x**2 - 2*z**2, 2*y*z + 2*x*w],
                       [2*x*z + 2*y*w, 2*y*z - 2*x*w, 1 - 2*x**2 - 2*y**2]]).T

check_quat(qs[0], qs[1], q_dot, quart2dcm, vec2quat)

λ₁ = quaternion(0.593794076962763, 0.542591160382069, 0.421246881221698, 0.418992233699113)
q3->q4: quaternion(0.593794076962763, 0.542591160382069, 0.421246881221698, 0.418992233699113)
модуль quaternion(0.593794076962763, 0.542591160382069, 0.421246881221698, 0.418992233699113) = 1.0)
λ₂ = quaternion(0.142355162244286, 0.0843646240423645, 0.804181513135995, 0.570885025134566)
λ₁∘λ₂ = quaternion(-0.539201193299804, 0.0308735946157745, 0.263075841464506, 0.799437299565957)

A(λ₁) = 
[[ 0.29399315 -0.04046055  0.95495077]
 [ 0.95471988  0.06008068 -0.29137649]
 [-0.04558484  0.99737318  0.0562918 ]] (type(A)=<class 'numpy.ndarray'>) 
Детерминант 1.0000000000000007, 
AA.T=
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# Копия старых результатов
"""
λ₁ = [0.59379408 0.54259116 0.42124688 0.41899223]
q3->q4: [0.5937940769627631, 0.5425911603820692, 0.4212468812216982, 0.4189922336991132]
модуль [0.5937940769627631, 0.5425911603820692, 0.4212468812216982, 0.4189922336991132] = 1.0)
λ₂ = [0.14235516 0.08436462 0.80418151 0.57088503]
λ₁∘λ₂ = [-0.53920119  0.03087359  0.26307584  0.7994373 ]

A(λ₁) = 
[[ 0.29399315  0.95471988 -0.04558484]
 [-0.04046055  0.06008068  0.99737318]
 [ 0.95495077 -0.29137649  0.0562918 ]] (type(A)=<class 'numpy.ndarray'>) 
Детерминант 1.0000000000000007, 
AA.T=
[[1 0 0]
 [0 1 0]
 [0 0 1]]
"""
None

*ТАК а почему матрица транспонированная-то была?*

<u>Проверка матрицы из кватернионов</u><br>
Поворот на $90^\circ$ вокруг оси $Oz$: 
$$\lambda = [\cos\frac{\varphi}{2}, 0, 0, \sin\frac{\varphi}{2}]$$
$$x\to y, \hskip20px y \to -x$$

In [39]:
import numpy as np
import quaternion

q1 = np.quaternion(1, 0, 0, 1).normalized()
A = quart2dcm(q1)
A = np.round(A).astype(np.int64)
print(f"A: \n{A}\n")

a = np.array([1, 0, 0])
print(f"x->y: {a} -> {A @ a}")

a = np.array([0, 1, 0])
print(f"y->-x: {a} -> {A @ a}")

A: 
[[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  1]]

x->y: [1 0 0] -> [0 1 0]
y->-x: [0 1 0] -> [-1  0  0]


##### Проверка работоспособности <u>символьного полиморфизма</u>

In [1]:
from __init__ import *
from sympy import *

vrs = kf.Variables()

r_n = vrs.spread('r', 'FemtoSat')
v_n = vrs.spread('v', 'FemtoSat')
w_n, mu_n, t_n = vrs.W_ORB, vrs.MU, 0
print(f"Численные параметры: r={r_n}, v={v_n}, t={t_n}")

r_s = kf.get_vars(name='r', n=3, numb=False)
v_s = kf.get_vars(name='v', n=3, numb=False)
q_s = kf.vec2quat(kf.get_vars(name='q', n=3, numb=False))
w_s, mu_s, rho, t_s = symbols("omega_0 mu rho t")
print(f"Символьные параметры: r={r_s}, v={v_s}, t={t_s}")

Инициализация проекта kiam-formation | Контекст: kiamformation
Используйте следующим способом: import kiamformation as kf
Параметры не могут быть загружены! Нет файла: kiamformation/data/config_choose.csv
Численные параметры: r=[-24.82487527 -96.00610803   5.54910576], v=[-0.08999732  0.02971298  0.08310143], t=0
Символьные параметры: r=Matrix([[r_x], [r_y], [r_z]]), v=Matrix([[v_x], [v_y], [v_z]]), t=t


###### Движение ХКУ

In [12]:
kf.my_print(f"Параметры ХКУ:", bold=True)
C_n = kf.get_c_hkw(r=r_n, v=v_n, w=w_n)
C_s = kf.get_c_hkw(r=r_s, v=v_s, w=w_s)
print(C_n)
display(C_s)

kf.my_print(f"\nРадиус-вектор из констант C: (t=t / t=0)", bold=True)
print(kf.r_hkw(C=C_n, w=w_n, t=t_n))
r_anw = kf.r_hkw(C=C_s, w=w_s, t=t_s)
display(r_anw)
display(r_anw.subs(t_s, 0))

kf.my_print(f"\nСкорость-вектор из констант C: (t=t / t=0)", bold=True)
print(kf.v_hkw(C=C_n, w=w_n, t=t_n))
v_anw = kf.v_hkw(C=C_s, w=w_s, t=t_s)
display(v_anw)
tmp = v_anw.subs(t_s, 0)
tmp.simplify()
display(tmp)

Параметры ХКУ:
[95.88474066719286, -40.756771080124935, -117.97587589628255, 99.65086785344182, 7.70289955995371, 56.47349145211723]


Matrix([
[   2*r_2 + v_0/omega_0],
[           v_2/omega_0],
[-3*r_2 - 2*v_0/omega_0],
[   r_0 - 2*v_2/omega_0],
[           v_1/omega_0],
[                   r_1]])


Радиус-вектор из констант C: (t=t / t=0)
[18.13732569 56.47349145 73.79360544]


Matrix([
[omega_0*t*(-6*r_2 - 3*v_0/omega_0) + r_0 - (-6*r_2 - 4*v_0/omega_0)*sin(omega_0*t) + 2*v_2*cos(omega_0*t)/omega_0 - 2*v_2/omega_0],
[                                                                                  r_1*cos(omega_0*t) + v_1*sin(omega_0*t)/omega_0],
[                                     4*r_2 + (-3*r_2 - 2*v_0/omega_0)*cos(omega_0*t) + 2*v_0/omega_0 + v_2*sin(omega_0*t)/omega_0]])

Matrix([
[r_0],
[r_1],
[r_2]])


Скорость-вектор из констант C: (t=t / t=0)
[-0.056082    0.00835538 -0.04420913]


Matrix([
[omega_0*(-6*r_2 - 3*v_0/omega_0) - 2*omega_0*(-3*r_2 - 2*v_0/omega_0)*cos(omega_0*t) - 2*v_2*sin(omega_0*t)],
[                                                           -omega_0*r_1*sin(omega_0*t) + v_1*cos(omega_0*t)],
[                                      -omega_0*(-3*r_2 - 2*v_0/omega_0)*sin(omega_0*t) + v_2*cos(omega_0*t)]])

Matrix([
[v_0],
[v_1],
[v_2]])

###### Поступательное движение

In [2]:
vrs = kf.Variables()
o = kf.Objects(vrs)

print(f"На высоте {round(vrs.HEIGHT // 1e3)} км плотность ρ={kf.get_atm_params(v=vrs, h=vrs.HEIGHT)[0]} кг/м³")
for drag in [False, True]:
    vrs.DYNAMIC_MODEL['aero drag'] = drag
    a_g_n = kf.get_full_acceleration(vrs=vrs, obj=o.f, i=0, r=r_n, v=v_n, w=w_n, mu=mu_n)
    kf.my_print(f"Ускорение в ОСК {'с торможением' if drag else 'без торможения'}:", bold=True, end='')
    print(a_g_n)

o.f.c_resist, vrs.V_ORB, o.f.mass = var('C v_0 m')
o.f.size = kf.get_vars(name='s', n=2)
o.f.q = [q_s]
o.f.r = [r_n]
o.f.v = [v_n]

for drag in [False, True]:
    vrs.DYNAMIC_MODEL['aero drag'] = drag
    a_g_s = kf.get_full_acceleration(vrs=vrs, obj=o.f, i=0, r=r_s, v=v_s, w=w_s, mu=mu_s, rho=rho)
    kf.my_print(f"Ускорение в ОСК {'с торможением' if drag else 'без торможения'}:", bold=True)
    display(a_g_s)

Параметры не могут быть загружены! Нет файла: kiamformation/data/config_choose.csv
Матрицы Ф:(6, 6), Q:(3, 3), P:(6, 6), D:(6, 3)
На высоте 400 км плотность ρ=6.404751331738951e-12 кг/м³
Ускорение в ОСК без торможения:[-0.00018833  0.00012327 -0.00018258]
Ускорение в ОСК с торможением:[-0.00019615  0.00012327 -0.00018258]
Ускорение в ОСК без торможения:


Matrix([
[                  -2*omega_0*v_z],
[                 -omega_0**2*r_y],
[3*omega_0**2*r_z + 2*omega_0*v_x]])

Ускорение в ОСК с торможением:


Matrix([
[           C*rho*s_0*s_1*(-v_0 - v_x)*sqrt(v_y**2 + v_z**2 + (v_0 + v_x)**2)*Abs(2*q_x**2 + 2*q_y**2 + 2*q_z**2 - 1)/(2*m) - 2*omega_0*v_z],
[                  -C*rho*s_0*s_1*v_y*sqrt(v_y**2 + v_z**2 + (v_0 + v_x)**2)*Abs(2*q_x**2 + 2*q_y**2 + 2*q_z**2 - 1)/(2*m) - omega_0**2*r_y],
[-C*rho*s_0*s_1*v_z*sqrt(v_y**2 + v_z**2 + (v_0 + v_x)**2)*Abs(2*q_x**2 + 2*q_y**2 + 2*q_z**2 - 1)/(2*m) + 3*omega_0**2*r_z + 2*omega_0*v_x]])

###### Вращательное движение

# ОСТАНОВИЛСЯ ЗДЕСЬ

##### Проверка соответствия <u>символьного и численного</u> матана

In [11]:
from sympy import *
import numpy as np
import quaternion

q1 = np.array([1, 2, 3, 4])
q2 = np.array([1, 2, 3, 4])

q1_n = np.quaternion(*q1).normalized()
q2_n = np.quaternion(*q2).normalized()
print(f"Численные кватернионы:\nq1 = {q1_n}\nq2 = {q2_n}\n")

q1_s = Matrix(q1 / np.linalg.norm(q1))
q2_s = Matrix(q2 / np.linalg.norm(q2))
print(f"Символьные кватернионы:\nq1 = {q1_s}\nq2 = {q2_s}")



Численные кватернионы:
q1 = quaternion(0.182574185835055, 0.365148371670111, 0.547722557505166, 0.730296743340221)
q2 = quaternion(0.182574185835055, 0.365148371670111, 0.547722557505166, 0.730296743340221)

Символьные кватернионы:
q1 = Matrix([[0.182574185835055], [0.365148371670111], [0.547722557505166], [0.730296743340221]])
q2 = Matrix([[0.182574185835055], [0.365148371670111], [0.547722557505166], [0.730296743340221]])
